basePath: /v1
host: localhost:8080
info:
  contact:
    email: harshvse@gmail.com
    name: Harsh Verma
    url: http://harshvse.in
  description: This is a sample server for a social media.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: /
  title: GoLang WebAPI Template With Chi-Postgres
  version: "1.0"
paths: {}
swagger: "2.0"
